### ISSUE TITLE
Logger limitation in cassandra cpp-driver

### ISSUE THREAD

**Issue by ahagh** [datastax/cpp-driver#155]
Exposing a method in the API to let the users to reinitialize the Cassandra logger again after calling cass_log_cleanup().

**Comment by avalanche123** [comment]
Please use the [CPP Driver Jira](https://datastax-oss.atlassian.net/browse/CPP) for reporting issues. Maintainers of this repo don't check GitHub issues and we'll disable them as soon as we get responses from all contributors about the CLA
